name: Release Trow

on:
  push:
    branch:
      - ecr-patch

jobs:
  release-trow:
    outputs:
      container-image: ${{ steps.build-images.outputs.container-image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push multi-arch image
        id: build-images
        run: ./docker/multi-arch.sh
