name: Release Trow

on:
  push:
    branches:
      - main

jobs:
  release-trow:
    outputs:
      container-image: ${{ steps.build-images.outputs.container-image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Pre-requirements
        run: |
          VERSION="v$(sed '/^version = */!d; s///;q' Cargo.toml | sed s/\"//g)"
          echo "TAG=$VERSION-amagi-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build and push container images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/amagioss/trow:${{ env.TAG }}
            ghcr.io/amagioss/trow:latest
        env:
          TAG: ${{ env.TAG }}
